### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by joshjohnsonux** [shakemno/sketch-replace-images#2]
I just installed this plugin to hopefully remove Photoshop from my workflow, but it doesn't appear to be working.  I have a sketch file with 4 art boards, and each art board has a placed image, where the image is in the same path directory ('workflow') as the sketch file.  I made changes to the individual images, and then open Sketch and ran the plugin.  When prompted for the path, I entered "../workflow" since that should work for both the image-to-sketch and sketch-to-image cases as it's unclear which one it's asking for.  But the result is that the first image in the sketch file is switched to Hidden, and no images are updated.  No error is thrown, and there's no visible way to trace to problem.

**Comment by shakemno** [comment]
I updated the code to work with sketch > 3.3 - please update the plugin and it would be great if you let me know if it works now. Also, if the sketch-file and the image are within the same directory, the path should be "./" (the default).

**Comment by joshjohnsonux** [comment]
Just uninstalled and reinstalled using Sketch Toolbox, and it DOES appear to be working correctly in Sketch 3.4.4 (17249).  Thanks for the quick response.
