### ISSUE TITLE
Enhancement Request: Persist Image Path

### ISSUE THREAD

**Issue by joshjohnsonux** [shakemno/sketch-replace-images#3]
This is a really useful plug-in and truthfully I can't imagine why it's not part of the core product.  Nice work!  Only usability issue I'm finding is that it's tedious to have to enter the path repeatedly.  It would be a nice improvement to persist that information, ideally on a per project basis if possible.

**Comment by shakemno** [comment]
Thanks again for your input. I just made some changes... Now the default directory is where the sketch-file is located. Though, you can still set a custom path which will then be used until you change it again. I couldn't (yet) find a good way to persist on a per project basis. Hope this works better, let me know what you think.

**Comment by joshjohnsonux** [comment]
Awesome!!!  Will check it out this week.

**Comment by shakemno** [comment]
I just replaced the manual path input with NSOpenPanel - should be more convenient to use now. Looking forward to your feedback.

**Comment by joshjohnsonux** [comment]
Seems to be an issue in my environment.  When I set the path, I get an
error that says:

​

**Comment by shakemno** [comment]
Sorry, but i think you forget to paste the error message. It would be really helpful if you could send it. Also, are you using the AppStore version?

**Comment by shakemno** [comment]
I fixed an issue - please let me know if it works as expected now.

**Comment by joshjohnsonux** [comment]
Sorry, I had posted it as an image that didn't come through.  Error said,
"There seems to be an issue with the path.  Please make sure you now(sic)
what you're doing."

I'm not using the AppStore version of Sketch, so it shouldn't be a sandbox
issue, if that helps.  I'll check out the new fix today, and let you know.

**Comment by joshjohnsonux** [comment]
Just ran a test with the new build and everything seems to be working as
expected.  Nice work!!!

**Comment by shakemno** [comment]
great :-) thanks again for your input and feedback

**Comment by joshjohnsonux** [comment]
Hi,

Just wanted to give you a heads up, that my recent update from 3.8 to 3.8.1
seems to have broken your plugin.  When I run the replace action, I get no
notification (good, bad or other) and obviously the replacement isn't
happening.  The ability to set the directory appears to be working
normally, and gives notification feedback as expected.

Thanks,
Josh

**Comment by shakemno** [comment]
Hey Josh,

thanks for the heads up - will take a look asap.

Best,
Manolis

**Comment by joshjohnsonux** [comment]
No problem.  I'm trying to figure out how to downgrade to 3.8, just to get
the plugin function back.  It's VERY useful.

**Comment by shakemno** [comment]
Hey, the issue should be fixed. Could you please let me know if it's also working for you?

**Comment by joshjohnsonux** [comment]
Just reinstalling from sketch toolbox should do?

**Comment by joshjohnsonux** [comment]
Working great!  Thanks.

Out of curiousity, what was the issue?  Anything I should yell at the
Sketch devs over?

**Comment by shakemno** [comment]
yes - but hang on a second. my commit doesn't show up in github yet... will let you know when it's up.

**Comment by shakemno** [comment]
As per the status page, this seems to be an issue at github - i can't see my changes ;-) but great that you can! The issue was a depreciated way of calling the replace method, take a look at the repo for more details.

All the best,
Manolis
