### ISSUE TITLE
Image gets resized on replace

### ISSUE THREAD

**Issue by SnowCreative** [shakemno/sketch-replace-images#5]
When I replace an image that I've resized on Sketch, it reverts to its original size. The modified sizes should be retained when replacing.

**Comment by shakemno** [comment]
Hey, thanks for letting me know. This is actually not an issue, this is the default behaviour of the replace action from Sketch. But it makes sense to keep the size, so i added this behaviour. Please update the plugin and have a try.

**Comment by SnowCreative** [comment]
Works great now! Thanks for the quick reply.
