### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by pedrotaquelim** [shakemno/sketch-replace-images#6]
Nothing happens. (?)

Sketch 3.9.1

**Comment by shakemno** [comment]
hi there,

really hard to tell what the issue could be without any more information. and it works for me (Sketch Version 39.1)?! did you not even see a notification saying that it couldn't update anything. please make sure to carefully read the instructions again and maybe reset to defaults... let me know if this is of any help. 

best mno

p.s.
you could also check the console app for more information.

**Comment by shakemno** [comment]
Since not getting any feedback on this issue, i will close it. If anyone else has any issues, please let me know.
