### ISSUE TITLE
Error: Sorry couldn't update images...

### ISSUE THREAD

**Issue by Jones-S** [shakemno/sketch-replace-images#7]
Hi there

I'm not sure whether this is the right plugin, but I want to replace an image all over my artboards. It appears multiple times and has always the same name.

I also don't really know how your plugin works, but when I try «Sketch Replace Images» nothing happens except for the error message «Sorry couldn't update images».
The same happens if I clearly select an image element.

I'm using the newest sketch version so far. (Version 39.1 (31720))

Any help welcome.

Cheers

**Comment by shakemno** [comment]
Hi there,

for the plugin in to work, it must know where the image(s) is located. If you set a custom path it will persit until you change it. Try using the settings to select the images directory. Hope that helps... please let me know.

p.s.
there is no need to select anything, the plugin will always look through all elements.

**Comment by shakemno** [comment]
hey, 

any progress on this issue?

**Comment by Jones-S** [comment]
Sorry, I never get any messages when someone commets issues...
Well, I don't even know how to set a path for an image. I just drag and drop them. From then on they are embedded in my sketchfile...
I also cannot find any settings for chosing an image directory.
Maybe you could give me another hint on that?

I'll try to enable email notification when receiving an issue-answer. Sorry again.

**Comment by shakemno** [comment]
No worries, 

the plugin needs to know where to get the images to update from. so if i setup a sketch project, i usually have a directory containing the sketch-file, and a sub-directory called "images" (for example). 

the default setting for the image path is on the level of the sketch-file, which means no sub-directory. in the described case, in the menu-bar you need to go to "Plugins/Sketch Replace Images/Sketch Replace Images Settings" which will open a select dialog where you can navigate to your project directory and the images directory. now you just have to hit "Set path". Everything should be setup now. In the dialog, you'll also find an options button, which has the reset default action.

If you just drag'n'drop images from several locations, this plugin is not of any help.

I hope this makes sense and you can get it to work. Let me know.

**Comment by Jones-S** [comment]
Alright. I got it now. I did not understand how to use it last time. 
Seems very logic to me now. Anyway, it works great. Thanks

**Comment by shakemno** [comment]
I am glad to hear that you could make it work for you!

All the best
