### ISSUE TITLE
Support Sketch 45 plugin update system

### ISSUE THREAD

**Issue by bomberstudios** [shakemno/sketch-replace-images#8]
Hi there!

This is a quick note to remind you that Sketch 45 will include a plugin update system.

It would be awesome if you could add support to it (it's really easy!) before Sketch 45 comes out. Ideally, you should release an update for your plugin while we're still in Sketch 44, so your users will have a nice & easy experience when 45 is released.

For more details, please check http://sketchplugins.com/d/229-updating-plugins and http://developer.sketchapp.com/introduction/updating-plugins/

Thanks in advance!

**Comment by idsn** [comment]
Yep, Sketch 441 does not work with this plugin :(

**Comment by shakemno** [comment]
Hey, thanks for the heads up – unfortunately I can't fix/update this in the near future, but will do asap. In the mean time, feel free to send pull request.

Cheers.

**Comment by shakemno** [comment]
**i finally fixed the issue and updated for 45+** 

_please let me know if you still find any issues_. 

all the best 
mno
